### ISSUE TITLE
Solr timeout errors

### ISSUE THREAD

**Issue by theorm** [impresso/impresso-middle-layer#431]
We should be retrying timeouts on Solr, but it seems that sometimes we don't or we fail after all retries:

```
[impresso.middle-layer] ERROR 500 GeneralError at search:find:  GeneralError: Headers Timeout Error
[impresso.middle-layer]     at preprocessSolrError (/impresso-middle-layer/dist/util/solr/errors.js:36:12)
[impresso.middle-layer]     at /impresso-middle-layer/dist/solr.js:311:48
[impresso.middle-layer] [Front End Error] (FeathersError:GeneralError) at "N/A":  - 
[impresso.middle-layer] [Front End Error] (FeathersError:GeneralError) at "N/A":  - 
```

**Comment by theorm** [comment]
Has not been seen in a while. Considering this fixed.
